Picking cherries and unflubbing the develop branch
Datateknologerna-vid-Abo-Akademi/date-website pull request #349
Opened 2023-07-13 19:08 UTC by JoarSabel

# CHERRY
> "git cherry-pick is a cursed practice"  -Einstein

---
Cherry picked a bunch of stuff from main develop branch, it works on my machine :)
ALSO:
- Added a (n)ew static image to the KK frontpage as per their request, sponsor logo, don't know why they want it there...
- Twisted the alumn/signup into a more KKish shape.

2023-07-13 19:11 UTC, JoarSabel commented
I put as many reviewers as I could, I expect my self esteem to be _**shattered**_ by the time you're all done reviewing this damn it!

2023-08-10 20:21 UTC, jaspnas approved these changes
Should be fine, please fix or mark as resolved the comments before merging

2023-08-10 20:21 UTC, jaspnas commented on members/templates/alumni_signup_email.html
> +    Kom även ihåg att hålla dina kontaktuppgifter uppdaterade via asg.abo.fi så att vi alltid når dig.
Is this supposed to be asg.abo.fi or kemistklubben.org?

2023-08-10 20:21 UTC, jaspnas commented on members/templates/alumni_signup_email_admin.html
Should this have some more details/ a description

2023-08-10 20:21 UTC, jaspnas commented on members/forms.py
> +    year_of_admission = forms.IntegerField(max_value=3000, label=_('Inskrivningsår'), required=False)
Should this have a minimum value as well?

2023-08-10 20:21 UTC, jaspnas commented on members/templates/alumni_signup_email.html
> +    Detta är ett automatiskt meddelande och skall ej besvaras.
Maybe consider adding a note about how to unsubscribe. I'm not a lawyer but seems like common courtesy.

2023-08-10 20:21 UTC, jaspnas commented on members/templates/signup.html
> +            {% endif %}
Should this be in swedish/translatable?

2023-08-10 20:21 UTC, jaspnas approved these changes
Should be fine, please fix or mark as resolved the comments before merging

2023-08-15 15:56 UTC, jaspnas requested changes

2023-08-15 15:56 UTC, jaspnas commented on members/templates/alumni_signup_email_admin.html
Just noticed this sends personal information through unencrypted email. #353

2023-08-18 20:37 UTC, jaspnas commented on members/templates/alumni_signup_email_admin.html
This should implement fix from #358

2023-08-21 08:15 UTC, nDny commented on members/templates/alumni_signup_email.html
> +    Kom även ihåg att hålla dina kontaktuppgifter uppdaterade via asg.abo.fi så att vi alltid når dig.
Should really just remove the "update" part for now since we don't really have that functionality in this version.

2023-08-21 08:17 UTC, nDny commented on members/templates/alumni_signup_email.html
> +    Detta är ett automatiskt meddelande och skall ej besvaras.
Could have something similar as we have in the account details page:
<img width="616" alt="image" src="https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/13031380/2eb2d5b5-39d5-4371-8daa-8e93ef9dffe7">

2023-08-21 08:19 UTC, nDny commented on members/templates/signup.html
> +            {% endif %}
This is just made in the same way as normal member signup, that button was also not translated 😄

2023-09-01 12:32 UTC, JoarSabel commented on members/templates/alumni_signup_email.html
> +    Kom även ihåg att hålla dina kontaktuppgifter uppdaterade via asg.abo.fi så att vi alltid når dig.
Removed

2023-09-01 12:32 UTC, JoarSabel commented on members/forms.py
> +    year_of_admission = forms.IntegerField(max_value=3000, label=_('Inskrivningsår'), required=False)
Some of these KK alumns are pretty old, you never know, but added 1900 as minimun :D

2023-09-01 12:32 UTC, JoarSabel commented on members/templates/alumni_signup_email.html
> +    Detta är ett automatiskt meddelande och skall ej besvaras.
Did the above.

2023-09-01 12:32 UTC, JoarSabel commented on members/templates/signup.html
> +            {% endif %}
Didn't

2023-09-01 12:36 UTC, JoarSabel commented on members/templates/alumni_signup_email_admin.html
Ripped this off. However, had some wacky issues (CSRF token stuffz) on the dev server where I couldn't test the functionality of the signup. Could put on QA to test idk.

2023-09-03 18:13 UTC, jaspnas approved these changes
Seems to work as intended. Should be tested in QA before pushing to prod

2023-09-05 09:39 UTC, merged