feat: Celery mail
Datateknologerna-vid-Abo-Akademi/date-website pull request #433
Opened 2023-12-30 01:17 UTC by jaspnas

Send email using celery workers

2024-01-09 19:16 UTC, Theoabw requested changes

2024-01-09 19:16 UTC, theoabw commented on core/utils.py
> +        print(f"Failed sending email to: {args[3] or kwargs.get('to', '')}")
Might be better to use logger.error() instead?

2024-01-09 19:16 UTC, theoabw commented on members/templates/registration/password_reset_email.html
>  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
Might wanna try `<a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}</a>` to ensure clickability?

2024-01-09 20:00 UTC, jaspnas commented on core/utils.py
> +        print(f"Failed sending email to: {args[3] or kwargs.get('to', '')}")
Good catch

2024-01-09 20:01 UTC, jaspnas commented on members/templates/registration/password_reset_email.html
>  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
Not going to change it in this PR, as it seems to work for now without it.

2024-01-11 20:36 UTC, Theoabw approved these changes

2024-01-25 14:33 UTC, merged