Fix/280 fix clean up the spaghetti in eventsviewspy
Datateknologerna-vid-Abo-Akademi/date-website pull request #453
Opened 2024-01-16 23:57 UTC by Theoabw

Check `avec_data = form.cleaned_data.copy()` and if it needs deepcopy or not. The functionality should basically be the same otherwise.

2024-01-17 11:21 UTC, andreedd commented
Would probably be good at some point to split up the validation in some kind of validation file. A bit like what was done on polls.

2024-01-17 12:15 UTC, Theoabw commented
> he functionality should basically be the same otherwise.

I totally didn't say that. Anyway, tests have passed after wayy too many tries. My fleshed out test member in tests.py is kind of unnecessary for this pr but might be useful in the future. I've tested it on localhost and basic event signup seems to be working fine. Logs don't give any weird errors at least.

2024-01-17 12:26 UTC, Theoabw commented
I still don't quite know how

`if self.object.sign_up and (request.user.is_authenticated
                                    and self.object.registration_is_open_members()
                                    and Member.objects.get(username=request.user.username).get_active_subscription() is not None
                                    or self.object.registration_is_open_others()
                                    or request.user.groups.filter(
                    name="commodore").exists()):`
                    
In the original code didn't throw an exception and my refactored version that defined the bools beforehand, but kept the if statement the same, did?

2024-02-06 18:56 UTC, jaspnas requested changes, later dismissed
Resolve the comments and rebase, looks like it's working for most normal use cases

2024-02-06 18:56 UTC, jaspnas commented on events/views.py
> +        return [self.template_name]
This wasn't a list previously, is this correct?

2024-02-06 18:56 UTC, jaspnas commented on events/tests.py
> +        SubscriptionPayment.objects.create(
Would be nice to have this as a variable for the class as well to be able to adjust the subscription status

2024-02-06 18:56 UTC, jaspnas commented on events/tests.py
> +            is_superuser=True
Set this to false, superusers should not sign up for events in production

2024-03-15 01:53 UTC, jaspnas requested changes, later dismissed
Needs more tests, should at least test the different types of members with different subscription payment statuses.

2024-03-20 15:23 UTC, Theoabw commented
> Needs more tests, should at least test the different types of members with different subscription payment statuses.

> Would probably be good at some point to split up the validation in some kind of validation file. A bit like what was done on polls.

I'm working on splitting up validation into a separate validation file. I noticed that the detail template was only checking for if user was validated and not if the user had an active subscription. This leads to members without an active subscription being able to see the registration form, but not being able to register to the event if self.object.registration_is_open_members() is true. 

Members without an active subscription shouldn't be able to see the registration form for an event that's only open for members.

2024-03-21 21:29 UTC, Theoabw commented
1. TODO: Captcha test
2. TODO: avec test
3. TODO: redirect link test
4. TODO: anonymous test
5. TODO: custom field test
6. TODO: max participants test

2024-03-23 14:40 UTC, jaspnas approved these changes

2024-03-23 14:40 UTC, jaspnas commented on events/tests.py
> +        self.assertEqual(incorrect.status_code, 200)
Should this be changed to return 401

Can be done as a later issue (create and resolve this comment)

2024-03-23 21:10 UTC, merged