exclude_indexing and update details template
Datateknologerna-vid-Abo-Akademi/date-website pull request #456
Opened 2024-01-17 14:23 UTC by Theoabw

The meta tag is in the body, but it should still work.

![image](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/12630429/8cecd6a1-05fd-4250-9c61-708e10fbcf47)

2024-01-17 16:30 UTC, jaspnas requested changes

2024-01-17 16:30 UTC, jaspnas commented on events/models.py
> +        grace_period = timedelta(days=1)  # Adjust this to change the grace period
Maybe adjust grace period to 7 days, and check that it's not in the old events list

2024-03-24 10:11 UTC, Theoabw commented
I might make tests for this later when I have time. Could do it during this pr or make a new issue later.

2024-03-24 14:34 UTC, jaspnas approved these changes
Tests can be created later

2024-03-24 14:34 UTC, jaspnas commented on events/models.py
> +        logger.debug(self)
Unnecessary debugs

2024-03-24 22:25 UTC, merged