Made edit form for info
Datateknologerna-vid-Abo-Akademi/date-website pull request #461
Opened 2024-01-20 16:45 UTC by Theoabw

2024-01-21 00:42 UTC, jaspnas commented on members/forms.py
> +            raise forms.ValidationError("This field is required.")
I think this should be validated by the EmailField being set as required

2024-01-21 00:42 UTC, jaspnas commented on members/views.py
> +from . import forms
Seems like an  unused import, also could be confused with how we usually import the django forms module

2024-01-21 00:42 UTC, jaspnas commented on members/forms.py
> +class MemberEditForm(forms.ModelForm):
Should maybe change the MemberupdateForm to AdminMemberUpdateForm for clarity

2024-01-21 11:49 UTC, theoabw commented on members/forms.py
> +            raise forms.ValidationError("This field is required.")
Yeah, I threw the whole email validation method in the trash bin.

2024-01-30 19:26 UTC, jaspnas commented on members/forms.py
> +    email = forms.EmailField(required=True)
Do we want users to be able to edit their email address?

2024-01-30 19:26 UTC, jaspnas commented on members/forms.py
> +        fields = ['email', 'first_name', 'last_name', 'phone', 'address', 'zip_code', 'city', 'country']
The form allows the user to set their first- and last name to blank, this should be fixed in the model by setting blank to false for it.

2024-02-06 16:02 UTC, jaspnas requested changes, later dismissed
Please resolve the earlier comments

2024-02-19 16:10 UTC, jaspnas approved these changes

2024-02-20 15:11 UTC, merged