Kk/cherry-pick
Datateknologerna-vid-Abo-Akademi/date-website pull request #470
Opened 2024-01-26 13:04 UTC by jaspnas

Cherry picking a bunch of stuff

2024-01-26 16:27 UTC, Nyygard approved these changes
Lgtm

2024-01-27 21:08 UTC, Theoabw requested changes

2024-01-27 21:08 UTC, Theoabw commented on events/urls.py
> +
Double re_path import?

2024-01-27 21:18 UTC, Theoabw commented
Also don't know if it's intended or not, but it doesn't pass kk-test at least for me

2024-01-27 21:22 UTC, Theoabw commented
![image](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/12630429/943f4452-091b-469b-94ef-1df91ddf5c3d)

2024-01-28 20:15 UTC, Theoabw commented
![image](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/12630429/aa3e85ab-9952-4e3a-b98f-27d9865d6578)

2024-03-26 23:21 UTC, jaspnas commented
Pls test on QA @Nyygard @Theoabw

2024-03-26 23:22 UTC, merged