Kk/develop -> KK/Main
Datateknologerna-vid-Abo-Akademi/date-website pull request #532
Opened 2024-03-26 23:30 UTC by jaspnas

Go to production

2024-03-27 15:12 UTC, Theoabw commented
Is it supposed to be failing several tests?

2024-03-27 17:16 UTC, jaspnas commented
> Is it supposed to be failing several tests?

KK tests are borked, they are wontfix as KK branch will be decomissioned after #330

2024-03-28 14:34 UTC, Theoabw requested changes

2024-03-28 14:34 UTC, Theoabw commented on members/templates/userinfo.html
> +                    <table class="table table-dark table-striped">
This should be changed. It's hard coded to use dark theme.

2024-03-28 18:13 UTC, merged