Feat/530 docker networks
Datateknologerna-vid-Abo-Akademi/date-website pull request #537
Opened 2024-03-28 19:01 UTC by Theoabw

2024-03-28 19:04 UTC, Theoabw commented
Continues from #524

2024-03-31 06:50 UTC, jaspnas commented
Encountering connection or DNS problems when testing with WSL, May be Windows being Windows or a race condition during startup. 

Basically nginx can't always find upstream

2024-04-08 10:14 UTC, jaspnas requested changes

2024-04-08 10:14 UTC, jaspnas commented on docker-compose.prod.yml
> +    build: .
Should not have build in prod

2024-04-18 23:05 UTC, jaspnas commented
Seems like DNS problems is just docker desktop on windows being unstable, going to test on my linux laptop tomorrow

2024-04-19 07:53 UTC, jaspnas approved these changes
Seems to work reliably on linux

![image](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/46525212/cf760f15-15d9-4226-981a-445b8df6dcc7)

2024-04-19 07:56 UTC, merged